In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [2]:
dataset = pd.read_csv('wine.csv')
dataset.head()

country  is_blend  is_dry  is_red  is_rose  is_sparkling  is_sweet  \
0   Italy         0       0       0        0             0         0   
1  France         0       0       1        0             0         0   
2   Italy         0       0       1        0             0         0   
3      US         0       0       1        1             0         0   
4      US         0       0       0        0             0         0   

   is_white  price            province              region_1     taster_name  \
0         0   30.0  Northeastern Italy            Alto Adige   Kerin O’Keefe   
1         0   22.0        Loire Valley              Sancerre      Roger Voss   
2         0   25.0             Tuscany      Chianti Classico      Roger Voss   
3         0   50.0          California  Russian River Valley  Virginie Boone   
4         0   38.0          California  Russian River Valley  Virginie Boone   

      variety    year  rating  
0   Sauvignon  2012.0       3  
1        Rosé  2014.0       2  
2  Sangiovese  2009.0       1  
3  Pinot Noir  2012.0       3  
4  Chardonnay  2013.0       3

In [3]:
X = dataset.iloc[:, [2, 8]].values
y = dataset.iloc[:, 14].values

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [7]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [9]:
print(X)

[[ 0. 30.]
 [ 0. 22.]
 [ 0. 25.]
 ...
 [ 1. 19.]
 [ 0. 32.]
 [ 0. 65.]]


In [10]:
print(y)

[3 2 1 ... 1 2 3]


In [11]:
lg = LogisticRegression(multi_class="multinomial", solver="newton-cg", max_iter=1000) 
lg.fit(X_train, y_train)

LogisticRegression(max_iter=1000, multi_class='multinomial', solver='newton-cg')

In [12]:
import xlrd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score
y_pred = lg.predict(X_test)

In [13]:
metrics.accuracy_score(y_pred, y_test)

0.48894472361809044

In [14]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train) #This is where the training is taking place
y_pred_logreg = logreg.predict(X_test) #Making predictions to test the model on test data
print('Logistic Regression Train accuracy %s' % logreg.score(X_train, y_train)) #Train accuracy
#Logistic Regression Train accuracy 0.8333333333333334
print('Logistic Regression Test accuracy %s' % accuracy_score(y_pred, y_test)) #Test accuracy
#Logistic Regression Test accuracy 0.5
print(confusion_matrix(y_test, y_pred_logreg)) #Confusion matrix
print(classification_report(y_test, y_pred_logreg)) #Classification Report

Logistic Regression Train accuracy 0.48190500125659713
Logistic Regression Test accuracy 0.48894472361809044
[[  0  45  31   4   0]
 [  0 443 457  91   1]
 [  0 292 807 295   2]
 [  0  43 605 673  13]
 [  0   0  26 129  23]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        80
           1       0.54      0.45      0.49       992
           2       0.42      0.58      0.49      1396
           3       0.56      0.50      0.53      1334
           4       0.59      0.13      0.21       178

    accuracy                           0.49      3980
   macro avg       0.42      0.33      0.34      3980
weighted avg       0.50      0.49      0.48      3980



D:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
